/**
 * @file HeaderRecord.h
 * @author Zach Houck
 * @date 2026-02-11
 * @brief Declares the HeaderRecord class used to build metadata for a length-indicated data file.
 */

#ifndef HEADERRECORD_H
#define HEADERRECORD_H

#include <iostream>
#include <fstream>
#include <filesystem>
#include <string>
#include <vector>

using namespace std;

class HeaderRecord
{
    private:

        int HeaderSizeBytes = 0; /**< Size of the serialized header record in bytes. */
        string FileStructureType = "CSV"; /**< Logical file structure identifier. */
        string Version = "1.0"; /**< File structure version for compatibility checks. */
        bool SizeFormatType = 0; /**< Size encoding mode: 0 = ASCII, 1 = binary. */
        bool SizeInclusion = true; /**< True when the size prefix includes its own bytes. */
        string PrimaryKeyIndex = "Key_index.txt"; /**< Name of the companion primary-key index file. */
        int RecordCount = 0; /**< Number of data records in the file (not including the original CSV header row). */
        int FieldCount = 6; /**< Number of data fields per record. */
        vector<string> Fields = {"ZipCode", "City", "State", "County", "Lat", "Long"}; /**< Field names in record order. */
        vector<string> FieldTypes = {"INT", "STRING", "STRING", "STRING", "FLOAT", "FLOAT"}; /**< Field type schema in record order. */
        int PrimaryKey = 1; /**< 1-based ordinal of the primary-key field. */

        string Header = ""; /**< Fully serialized header line generated by this class. */

    public:
    /**
     * @brief Constructs a HeaderRecord by inspecting an input CSV file.
     * @param InFile Path to the source CSV file used to determine record count.
     */
    HeaderRecord(const string& InFile);

    /**
     * @brief Returns the serialized header record string.
     * @return Header record text ready to be written to the output data file.
     */
    string GetHeader() const;


};

#endif