/**
 * @file HeaderRecord.h
 * @author Zach Houck
 * @date 2026-02-11
 * @brief Declares the HeaderRecord class used to build metadata for a length-indicated data file.
 */

#ifndef HEADERRECORD_H
#define HEADERRECORD_H

#include <iostream>
#include <fstream>
#include <filesystem>
#include <string>
#include <vector>

using namespace std;

class HeaderRecord
{
    friend class HeaderBuffer;

    private:








        int HeaderSizeBytes = 0; /**< Size of the serialized header record in bytes. */
        string FileStructureType = "CSV"; /**< Logical file structure identifier. */
        string Version = "1.0"; /**< File structure version for compatibility checks. */
        bool SizeFormatType = 0; /**< Size encoding mode: 0 = ASCII, 1 = binary. */
        bool SizeInclusion = true; /**< True when the size prefix includes its own bytes. */
        string PrimaryKeyIndex = "Key_index.txt"; /**< Name of the companion primary-key index file. */
        int RecordCount = 0; /**< Number of data records in the file (not including the original CSV header row). */
        int FieldCount = 6; /**< Number of data fields per record. */
        vector<string> Fields = {"ZipCode", "City", "State", "County", "Lat", "Long"}; /**< Field names in record order. */
        vector<string> FieldTypes = {"INT", "STRING", "STRING", "STRING", "FLOAT", "FLOAT"}; /**< Field type schema in record order. */
        int PrimaryKey = 1; /**< 1-based ordinal of the primary-key field. */

        string Header = ""; /**< Fully serialized header line generated by this class. */

        /** Rebuilds the serialized header string from the current field values. */
        void RebuildHeader();




        ///////////////////////////////////
        // Project 3.0 Modifications
        ///////////////////////////////////
        //
        //  Use both a block buffer class and a record buffer class to read and unpack Zip Code Records from a sequence set block into a sorted container of record objects.
        //
        //      -The block buffer unpacks a record from a block into a record buffer.
        //
        //      -The record buffer unpacks fields from the record buffer into a record object.
        //
        //
        //    Modify your data file header record buffer class to read and write the blocked sequence set data file header record
        //
        
        int BlockSize = 512;
        int MinBlockCapacity = 50;
        int BlockCount = 0;
        int availListHeadRBN = 0;
        int ActiveListHeadRBN = 0;
        bool StaleFlag = false;




        ////////////////////////////////////



    public:
    /**
     * @brief Constructs a default header record that can later be populated by parsing.
     */
    HeaderRecord() = default;

    /**
     * @brief Constructs a HeaderRecord by inspecting an input CSV file.
     * @param InFile Path to the source CSV file used to determine record count.
     */
    HeaderRecord(const string& InFile);

    /**
     * @brief Returns the serialized header record string.
     * @return Header record text ready to be written to the output data file.
     */
    string GetHeader() const;



    // Project 3 //
    //

    /**
     * @brief
     * @param@ 
     * @param@
     */
    bool WriteHeader(std::fstream& out, const HeaderRecord& header);

    bool ReadHeader(std::fstream& in, HeaderRecord& header);
    
};

#endif